"""
app/state.py — Shared pipeline state for Nirvaah AI LangGraph pipeline.

This TypedDict is the contract between all agents — every key that any 
agent reads or writes is declared here.
"""

from typing import TypedDict, Optional


class PipelineState(TypedDict):

    # --- Input fields (set by webhook.py before pipeline starts) ---
    transcript: str
    # The raw text that will be processed. For voice input this is the
    # ElevenLabs transcription. For text input this is the typed message.
    # For image input this is the OCR output. Always a plain string.

    sender_phone: str
    # The ASHA worker's WhatsApp number. Used by sync_agent to associate
    # the record with the right worker. Format: "+919876543210"

    input_source: str
    # How the input arrived: "voice", "text", or "image".
    # Set by process_input() in extraction.py before the graph runs.

    ocr_text: str
    # The raw text extracted by OCR before cleaning. Only populated when
    # input_source is "image". Empty string otherwise. Useful for debugging
    # OCR misreads during demo.

    # --- Agent 1 output (set by extraction_node) ---
    extracted_fields: dict
    # The structured JSON dict from Groq. Contains bp_systolic, hemoglobin,
    # visit_type, overall_confidence, field_confidence, etc.
    # Empty dict {} if extraction failed.

    # --- Agent 2 output (set by validation_node) ---
    validated_fields: dict
    # The extracted_fields dict after range checking and Kerala protocol
    # validation. May have additional flags added like "anemia_flag": True.
    # Empty dict {} if validation has not run yet.

    clarification_needed: bool
    # Set to True by validation_node if overall_confidence < 0.70 or if
    # any required field fails its range check.

    clarification_question: str
    # The WhatsApp-friendly question to send back to the ASHA worker when
    # clarification_needed is True. e.g. "BP reading unclear — please reply
    # with systolic/diastolic (e.g. 110/70)". Empty string otherwise.

    validation_alerts: list
    # List of clinical alert strings generated by validation_node.
    # e.g. ["anemia_flag", "high_bp_alert", "pre_eclampsia_risk"]
    # Empty list [] if no alerts.

    # --- Agent 3 output (set by form_agent_node) ---
    mapped_forms: dict
    # Dict with three keys: "hmis", "mcts", "kerala_hims".
    # Each value is a dict of field mappings ready for that system.
    # e.g. {"hmis": {"ANC_BP": "110/70", ...}, "mcts": {...}, ...}

    # --- Agent 4 output (set by sync_node) ---
    sync_status: dict
    # Tracks write status per destination.
    # e.g. {"supabase": "success", "google_sheets": "pending",
    #        "record_id": "uuid-here"}

    # --- Agent 5 output (set by anomaly_node) ---
    anomaly_score: float
    # 0.0 to 1.0. Higher = more anomalous. Threshold is 0.6 (from .env).
    # 0.0 means no anomaly detected or model not yet run.

    anomaly_flags: list
    # List of specific rule-based flags triggered.
    # e.g. ["high_submission_velocity", "duplicate_fields", "off_hours"]
    # Empty list [] if no flags.

    # --- Agent 6 output (set by insights_node) ---
    dropout_risk: float
    # 0.0 to 1.0 dropout risk score from XGBoost model.
    # 0.0 means low risk or model not yet run.

    eligible_schemes: list
    # List of government scheme dicts the beneficiary qualifies for.
    # e.g. [{"name": "PMMVY", "reason": "First live birth, ANC registered"}]
    # Empty list [] if no eligible schemes found.

    risk_summary: str
    # 2-sentence human-readable summary of dropout risk generated by Groq.
    # Only populated when dropout_risk > 0.70. Empty string otherwise.

    # --- Pipeline metadata ---
    errors: list
    # Accumulated list of error strings from any node that failed.
    # Nodes should append to this list, never overwrite it.
    # e.g. ["extraction: json_parse_failed", "sync: supabase_timeout"]

    pipeline_complete: bool
    # Set to True by the last node that runs successfully.
    # webhook.py checks this to know the pipeline finished cleanly.


def get_initial_state(
    transcript: str,
    sender_phone: str,
    input_source: str = "text",
    ocr_text: str = ""
) -> PipelineState:
    """
    Returns a fully populated PipelineState with safe default values.
    Used by pipeline.py to initialise state before the graph runs.
    """
    return PipelineState(
        transcript=transcript,
        sender_phone=sender_phone,
        input_source=input_source,
        ocr_text=ocr_text,
        extracted_fields={},
        validated_fields={},
        clarification_needed=False,
        clarification_question="",
        validation_alerts=[],
        mapped_forms={},
        sync_status={},
        anomaly_score=0.0,
        anomaly_flags=[],
        dropout_risk=0.0,
        eligible_schemes=[],
        risk_summary="",
        errors=[],
        pipeline_complete=False
    )
