# Nirvaah AI - Global Security Constants
# Reference: Log File Structures & Security Schemas v1.0

# --- Log Names (Master Index) ---
WEBHOOK_RAW = "LOG-01"
PIPELINE_EVENT = "LOG-02"
AUDIT_CHAIN = "LOG-03"
ENCRYPTED_RECORD = "LOG-04"
ACCESS_EVENT = "LOG-05"
ANOMALY_ALERT = "LOG-06"
SYNC_STATUS = "LOG-07"

# --- Pipeline Stage Names ---
STAGE_01_INPUT = "INPUT_CAPTURE"
STAGE_02_TRANSCRIPTION = "WHISPER_TRANSCRIPTION"
STAGE_03_OCR = "OCR_EXTRACTION"
STAGE_04_INTENT = "INTENT_AGENT"
STAGE_05_VALIDATION = "VALIDATION_AGENT"
STAGE_06_FORM = "FORM_AGENT"
STAGE_07_SYNC = "SYNC_AGENT"
STAGE_08_AUDIT = "AUDIT_AGENT"
STAGE_09_ANOMALY = "ANOMALY_AGENT"
STAGE_10_INSIGHTS = "INSIGHTS_AGENT"
STAGE_11_NOTIFICATION = "NOTIFICATION"

# --- Hashing & Encryption ---
HASH_ALGO = "sha256"
HASH_PREFIX = "sha256:"
ENCRYPT_ALGO = "AES-256-GCM"
KDF = "PBKDF2-SHA256"
KDF_ITERATIONS = 480000
GENESIS_HASH = "0" * 64

# --- ID Prefixes & Formats ---
RECORD_ID_PREFIX = "NV-"
SESSION_ID_PREFIX = "sess_"
WORKER_ID_PREFIX = "ASHA-"
TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ" # ISO 8601 UTC

# --- Status Values ---
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILURE = "FAILURE"
STATUS_PENDING = "PENDING"
